name: Factions
version: ${project.version}
main: com.massivecraft.factions.P
authors: [OG: Olof Larsson, Brett Flannigan, drtshock | TC: iReversal]
softdepend: [PlayerVaults, PermissionsEx, Permissions, Essentials, EssentialsChat, HeroChat, iChat, LocalAreaChat, LWC, nChat, ChatManager, CAPI, AuthMe, Vault, Spout, WorldEdit, WorldGuard, AuthDB, CaptureThePoints, CombatTag, dynmap]
commands:
  factions:
    description: Reference command for Factions.
    aliases: [f]
permissions:
  tcfactions.kit.admin:
    description: All faction permissions.
    children:
      tcfactions.kit.mod: true
      tcfactions.config: true
      tcfactions.lock: true
      tcfactions.reload: true
      tcfactions.save: true
      tcfactions.modifypower: true
      tcfactions.ahome: true
      tcfactions.setmaxvaults: true
  tcfactions.*:
    description: This is just an alias for factions.kit.admin
    children:
      factions.kit.admin: true
  tcfactions.kit.mod:
    description: All faction permissions but configuration and persistance.
    children:
      tcfactions.kit.halfmod: true
      tcfactions.disband.any: true
      tcfactions.setpeaceful: true
      tcfactions.setpermanent: true
      tcfactions.setpermanentpower: true
      tcfactions.powerboost: true
      tcfactions.sethome.any: true
      tcfactions.money.*: true
      tcfactions.join.any: true
      tcfactions.join.others: true
      tcfactions.admin.any: true
      tcfactions.mod.any: true
  tcfactions.kit.halfmod:
    description: Zones, bypassing, kicking, and chatspy
    children:
      tcfactions.kit.fullplayer: true
      tcfactions.managesafezone: true
      tcfactions.managewarzone: true
      tcfactions.bypass: true
      tcfactions.kick.any: true
      tcfactions.ownershipbypass: true
      tcfactions.chatspy: true
      tcfactions.show.bypassexempt: true
  tcfactions.kit.fullplayer:
    default: true
    description: Can also create new factions.
    children:
      tcfactions.kit.halfplayer: true
      factions.create: true
  tcfactions.kit.halfplayer:
    description: Can do all but create factions.
    children:
      tcfactions.admin: true
      tcfactions.autoclaim: true
      tcfactions.chat: true
      tcfactions.claim: true
      tcfactions.claim.line: true
      tcfactions.claim.radius: true
      tcfactions.deinvite: true
      tcfactions.description: true
      tcfactions.disband: true
      tcfactions.help: true
      tcfactions.home: true
      tcfactions.invite: true
      tcfactions.join: true
      tcfactions.kick: true
      tcfactions.leave: true
      tcfactions.list: true
      tcfactions.map: true
      tcfactions.mod: true
      tcfactions.money.kit.standard: true
      tcfactions.noboom: true
      tcfactions.open: true
      tcfactions.owner: true
      tcfactions.ownerlist: true
      tcfactions.power: true
      tcfactions.power.any: true
      tcfactions.relation: true
      tcfactions.sethome: true
      tcfactions.show: true
      tcfactions.stuck: true
      tcfactions.tag: true
      tcfactions.title: true
      tcfactions.version: true
      tcfactions.unclaim: true
      tcfactions.unclaimall: true
      tcfactions.scoreboard: true
      tcfactions.showinvites: true
      tcfactions.seechunk: true
      tcfactions.monitorlogins: true
      tcfactions.top: true
      tcfactions.togglealliancechat: true
      tcfactions.vault: true
  tcfactions.admin:
    description: hand over your admin rights
  tcfactions.admin.any:
    description: give or revoke admin status for any player in any faction
  tcfactions.announce:
    description: announce things to the peasants
  tcfactions.autoclaim:
    description: auto-claim land as you walk around
  tcfactions.bypass:
    description: enable admin bypass mode
  tcfactions.chat:
    description: change chat mode
  tcfactions.chatspy:
    description: enable admin chat spy mode
  tcfactions.claim:
    description: claim land where you are standing
  tcfactions.claim.radius:
    description: claim land in a large radius
  tcfactions.config:
    description: change a conf.json setting
  tcfactions.create:
    description: create a new faction
  tcfactions.deinvite:
    description: remove a pending invitation
  tcfactions.description:
    description: change the faction description
  tcfactions.disband:
    description: disband a faction
  tcfactions.disband.any:
    description: disband another faction
  tcfactions.help:
    description: display a help page
  tcfactions.home:
    description: teleport to the faction home
  tcfactions.invite:
    description: invite a player to your faction
  tcfactions.join:
    description: join a faction
  tcfactions.join.any:
    description: join any faction, bypassing invitation process for closed factions
  tcfactions.join.others:
    description: specify another player in the join command, to move them to the specified faction
  tcfactions.kick:
    description: kick a player from the faction
  tcfactions.kick.any:
    description: kick anyone from any faction
  tcfactions.leave:
    description: leave your faction
  tcfactions.list:
    description: see a list of the factions
  tcfactions.lock:
    description: lock all write stuff
  tcfactions.managesafezone:
    description: claim land as a safe zone and build/destroy within safe zones
  tcfactions.managewarzone:
    description: claim land as a war zone and build/destroy within war zones
  tcfactions.map:
    description: show the territory map, and set optional auto update
  tcfactions.mod:
    description: give or revoke moderator rights
  tcfactions.mod.any:
    description: give or revoke moderator rights for any player in any faction
  tcfactions.money.balance:
    description: show your factions current money balance
  tcfactions.money.balance.any:
    description: show money balance for factions other than your own
  tcfactions.money.deposit:
    description: deposit money into a faction bank
  tcfactions.money.withdraw:
    description: withdraw money from your faction bank
  tcfactions.money.withdraw.any:
    description: withdraw money from your factions other than your own
  tcfactions.money.f2f:
    description: transfer money from faction to faction
  tcfactions.money.f2p:
    description: transfer money from faction to player
  tcfactions.money.p2f:
    description: transfer money from player to faction
  tcfactions.money.kit.standard:
    children:
      factions.money.balance: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.withdraw: true
      factions.money.f2f: true
      factions.money.f2p: true
      factions.money.p2f: true
  tcfactions.money.*:
    children:
      factions.money.kit.standard: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.withdraw: true
      factions.money.withdraw.any: true
      factions.money.f2f: true
      factions.money.f2p: true
      factions.money.p2f: true
  tcfactions.noboom:
    description: toggle explosions (peaceful factions only)
  tcfactions.open:
    description: switch if invitation is required to join
  tcfactions.owner:
    description: set ownership of claimed land
  tcfactions.ownerlist:
    description: list owner(s) of this claimed land
  tcfactions.ownershipbypass:
    description: bypass ownership restrictions within own faction's territory
  tcfactions.setpeaceful:
    description: designate a faction as peaceful
  tcfactions.setpermanent:
    description: designate a faction as permanent
  tcfactions.setpermanentpower:
    description: set permanent power for a faction
  tcfactions.stuck:
    description: teleports player outside a faction
  tcfactions.power:
    description: show player power info
  tcfactions.power.any:
    description: view an other players power level
  tcfactions.powerboost:
    description: apply permanent power bonus/penalty to specified player or faction
  tcfactions.relation:
    description: set relation wish to another faction
  tcfactions.reload:
    description: reload data file(s) from disk
  tcfactions.save:
    description: save all data to disk
  tcfactions.sethome:
    description: set the faction home
  tcfactions.sethome.any:
    description: set faction home for another faction
  tcfactions.show:
    description: show faction information
  tcfactions.show.bypassexempt:
    description: show exempt faction information
  tcfactions.tag:
    description: change the faction tag
  tcfactions.title:
    description: set or remove a players title
  tcfactions.version:
    description: see the version of the plugin
  tcfactions.unclaim:
    description: unclaim the land where you are standing
  tcfactions.unclaimall:
    description: unclaim all of your factions land
  tcfactions.scoreboard:
    description: ability to toggle scoreboards
  tcfactions.showinvites:
    description: show pending invites to your faction
  tcfactions.seechunk:
    description: see the chunk you stand in
  tcfactions.setwarp:
    description: set a warp for your faction
  tcfactions.warp:
    description: access your faction warps
  tcfactions.modifypower:
    description: modify other player's power
  tcfactions.monitorlogins:
    description: monitor join and leaves of faction members
  tcfactions.claim.line:
    description: claim in a line
  tcfactions.top:
    description: sort factions
  tcfactions.togglealliancechat:
    description: toggle alliance chat on and off
  tcfactions.dontlosepoweroffline:
    description: Don't lose power for being offline.
  tcfactions.ahome:
    description: Ability to send players to their faction home.
  tcfactions.autoleavebypass:
    description: Bypass autoleave.
  tcfactions.vault:
    description: Access faction vault.
  tcfactions.setmaxvault:
    description: Set a faction's max vaults.
